version: "2"

services:
  web:
    image: tuleap/tuleap-community-edition
    hostname: localhost
    restart: always
    ports:
      - "80:80"
      - "443:443"
      # - "22:22"
    volumes:
      - tuleap-data:/data
    depends_on:
      - db
      - redis
      - mailhog
    environment:
      - TULEAP_FQDN=localhost
      - TULEAP_SYS_DBHOST=db
      - TULEAP_SYS_DBPASSWD=12345678
      - SITE_ADMINISTRATOR_PASSWORD=12345678
      - DB_ADMIN_USER=root
      - DB_ADMIN_PASSWORD=12345678
      - TULEAP_FPM_SESSION_MODE=redis
      - TULEAP_REDIS_SERVER=redis

  # This is for test purpose only. It's not advised to run a production database as a docker container
  db:
    image: mysql:8.0
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--sql-mode=NO_ENGINE_SUBSTITUTION",
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - db80-data:/var/lib/mysql

  # This is for test purpose only. It's not advised to run a production database as a docker container
  redis:
    image: redis:6
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --auto-aof-rewrite-percentage 20 --auto-aof-rewrite-min-size 200kb

  # This is for test purpose only. Mailhog is there to capture email traffic
  mailhog:
    image: mailhog/mailhog

volumes:
  tuleap-data:
  db80-data:
  redis-data:
