# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    # image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    hostname: 'localhost'
    container_name: jenkins
    ports:
        - '8080:8080'
        - '8443:443'
    build: .
    environment:
      - "JENKINS_ADMIN_ID=admin"
      - "JENKINS_ADMIN_PASSWORD=minhthu"
    volumes:
      # - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker