{
 "title": "Home",
 "time": { "from": "2023-04-07T03:20:11.152Z", "to": "2023-04-07T03:22:14.279Z" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "500ms,1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "resource_usage{type=\"ram\"}/(1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "resource_usage{type=\"cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_kafka_kafka_msg_consuming_success_count{job=\"prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_kafka_kafka_msg_consuming_duration_ms_bucket[1m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending inflight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pending_in_flight_requests{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(pending_requests_total{job=\"prometheus\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chan inflight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "chan_in_flight_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chan total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(chan_requests_total{job=\"prometheus\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "go_threads{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ae inflight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "ae_in_flight_requests{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ae total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(ae_requests_total{job=\"prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ae latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ae_request_duration_seconds_bucket[1m])) by (le,operation))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gettingstarted",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {}
   ]
  }
 ]
}