# docker-compose.yaml
version: "3.8"
services:
  jenkins:
    privileged: true
    user: root
    restart: always
    hostname: "localhost"
    container_name: jenkins_config
    ports:
      - "9000:80"
    build: .
    environment:
      - "JENKINS_ADMIN_ID=admin"
      - "JENKINS_ADMIN_PASSWORD=minhthu"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
